services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # cache:
  #   image: redis
  #   restart: unless-stopped
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   volumes:
  #     - cache:/data

volumes:
  pgdata:
  # cache:
  #   driver: local
